### ISSUE TITLE
TensorRT C++ support 

### ISSUE THREAD

**Issue by Gaozhongpai** [OroChippw/LightGlue-OnnxRunner#16]
Hi, thanks for sharing the code. Are you planning to have TensorRT support in C++? Thanks again.

**Comment by Gaozhongpai** [comment]
I added:

 ```
            std::cout << "[INFO] OrtSessionOptions Append TensorRTProvider" << std::endl;
            OrtTensorRTProviderOptions trt_options{};

            // note: for bool type options in c++ API, set them as 0/1
            trt_options.device_id = 0;
            trt_options.trt_max_workspace_size = 4294967296;
            trt_options.trt_max_partition_iterations = 1000;
            trt_options.trt_min_subgraph_size = 5;
            trt_options.trt_fp16_enable = 1;
            trt_options.trt_int8_enable = 0;
            trt_options.trt_int8_use_native_calibration_table = 1;
            trt_options.trt_engine_cache_enable = 1;
            trt_options.trt_engine_cache_path = "trtcache";
            trt_options.trt_dump_subgraphs = 1;
            session_options.AppendExecutionProvider_TensorRT(trt_options);
```

I can run the program after adding the `TensorRTProvider`, but  `trtcache` folder is empty and no engine file is cached.

**Comment by OroChippw** [comment]
> I added:
> 
> ```
>            std::cout << "[INFO] OrtSessionOptions Append TensorRTProvider" << std::endl;
>            OrtTensorRTProviderOptions trt_options{};
> 
>            // note: for bool type options in c++ API, set them as 0/1
>            trt_options.device_id = 0;
>            trt_options.trt_max_workspace_size = 4294967296;
>            trt_options.trt_max_partition_iterations = 1000;
>            trt_options.trt_min_subgraph_size = 5;
>            trt_options.trt_fp16_enable = 1;
>            trt_options.trt_int8_enable = 0;
>            trt_options.trt_int8_use_native_calibration_table = 1;
>            trt_options.trt_engine_cache_enable = 1;
>            trt_options.trt_engine_cache_path = "trtcache";
>            trt_options.trt_dump_subgraphs = 1;
>            session_options.AppendExecutionProvider_TensorRT(trt_options);
> ```
> 
> And comment: `// session_options.AppendExecutionProvider_CUDA(cuda_options);` It is working now.

Since I am not familiar with tensorRT, the relevant inference code will not be provided in the near future. For the engine model, you can get it here https://github.com/fabio-sim/LightGlue-ONNX/releases/tag/v0.1.3 . If you can provide relevant inference code for tensorRT, you are welcome to initiate a merge request. Thank you for your attention to this repository

**Comment by newforrestgump001** [comment]
there is fatal memory leak in main.exe. Please help to fix it when you're free. Thank u a lot!

**Comment by newforrestgump001** [comment]
After updating cuda11.0 to cuda11.7, there is no memory leak any more. Thank u again!
