### ISSUE TITLE
Hope to support Linux platform

### ISSUE THREAD

**Issue by JingruiYu** [OroChippw/LightGlue-OnnxRunner#19]
Hope to add support for the Linux platform

![image](https://github.com/OroChippw/LightGlue-OnnxRunner/assets/18253910/a3a57277-2946-4e88-81c2-bb7b72fe1f7d)

**Comment by OroChippw** [comment]
Thank you for your help. Since I do not have a Linux-related development environment, I cannot provide Linux-related support for the time being. It may be added in the future. If you have relevant code, you are also welcome to initiate a pull request.😊

**Comment by JingruiYu** [comment]
Ack
