### ISSUE TITLE
error: cannot bind non-const lvalue reference of type 'cv::Mat&' to an rvalue of type 'cv::Mat'

### ISSUE THREAD

**Issue by JingruiYu** [OroChippw/LightGlue-OnnxRunner#20]
src/LightGlueOnnxRunner.cpp line 84,
`cv::Mat resultImage = NormalizeImage(ResizeImage(tempImage ,cfg.image_size , scale , fn , interp));` , encounter error,
`error: cannot bind non-const lvalue reference of type 'cv::Mat&' to an rvalue of type 'cv::Mat'`.
Maybe it could be,
```
cv::Mat reszieImage = ResizeImage(tempImage ,cfg.image_size , scale , fn , interp);
cv::Mat resultImage = NormalizeImage(reszieImage);
```

**Comment by OroChippw** [comment]
Thanks for using this project and asking this question and its solution, if you are using C++11 or higher, using std::move is also a good option😊

**Comment by JingruiYu** [comment]
Thanks!
